#baseURL = "https://mikepruett3.github.io/"
baseURL = "https://www.nixdevil.com/"
languageCode = "en-us"
title = "A haven for Unix & Linux deviants"
theme = "hugo-theme-bootstrap"
#sectionPagesMenu = "main"

paginate = 5
enableRobotsTXT = true
enableEmoji = true

[params]
color = "dark"
palette = "green"
math = true
toc = true

[author]
name = "Mike Pruett"
avatar = "/uploads/avatar.jpg"
bio = "Super passionate about Linux, Open Source Software, Beer, and Life."
company = "Nixdevil.com"
location = "Texas"

[social]
github = "mikepruett3"
reddit = "Human_Cartographer"
linkedin = "in/mpruett"
youtube = "UCZ-i9SPvPLMQmk1sognhu_A"
untappd = "mikepruett3"

[[menu.main]]
name = "Dropdown"
identifier = "dropdown"
pre = '<i class="fas fa-fw fa-chevron-circle-down"></i>'
#[[menu.main]]
#  id = "wiki"
#  parent = "dropdown"
#  name = "Mike's Wiki"
#  url = "/mikes-wiki/"
#  pre = '<i class="fab fa-fw fa-wikipedia-w"></i>'
[[menu.main]]
  id = "github"
  parent = "dropdown"
  name = "github"
  url = "https://github.com/mikepruett3"
  pre = '<i class="fab fa-fw fa-github"></i>'