baseURL = "https://mikepruett3.github.io/"
languageCode = "en-us"
title = "A haven for Unix & Linux deviants"
theme = "hugo-theme-bootstrap"

paginate = 5
enableRobotsTXT = true
enableEmoji = true

[params]
color = "dark"
palette = "green"
math = true
toc = true

[author]
name = "Mike Pruett"
avatar = "/uploads/avatar.jpg"
bio = "A haven for Unix & Linux deviants"
company = "Nixdevil.com"
location = "Texas"

[social]
github = "mikepruett3"
reddit = "Human_Cartographer"
linkedin = "in/mpruett"
youtube = "UCZ-i9SPvPLMQmk1sognhu_A"